name: Generate image sitemap

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "17 3 * * *"
  workflow_dispatch:

permissions:
  contents: write   # 👈 nécessaire pour git push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Generate sitemap.xml
        run: |
          python scripts/generate_sitemap.py

      - name: Commit & push if changed
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add sitemap.xml
            git commit -m "chore: update sitemap.xml"
            git push
          else
            echo "No changes to commit."
          fi

name: Generate image sitemap

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "17 3 * * *"   # 1 fois par jour (03:17 UTC)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # pour lire les dates git des fichiers

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Generate sitemap.xml
        run: |
          python scripts/generate_sitemap.py

      - name: Commit & push if changed
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add sitemap.xml
            git commit -m "chore: update sitemap.xml"
            git push
          else
            echo "No changes to commit."
          fi
